### ISSUE TITLE
add contrubter error

### ISSUE THREAD

**Issue by zeyad-k** [MohmmedAshraf/laravel-translations#82] opened 2024-02-28 12:59 UTC
![image](https://github.com/MohmmedAshraf/laravel-translations/assets/144251652/37b8fcd2-73cc-4cc5-9930-3c6b18f742f3)
 it always returns this

**Comment by MohmmedAshraf** [comment] 2024-03-01 04:24
Duplicate of #79

**Closed by MohmmedAshraf** 2024-03-01 04:24 UTC
