### ISSUE TITLE
Load time 4.5s

### ISSUE THREAD

**Issue by dkvadratu** [MohmmedAshraf/laravel-translations#2] opened 2022-11-18 22:16 UTC
Hey, very nice tool! I have tested on empty Laravel project with _Breeze/Livewire_. And your package adds 4 - 4.5s load to every route.

I could not find whos is making _Application load_ so long. Any ideas?

**Comment by MohmmedAshraf** [comment] 2022-11-18 22:31
Hi, @dkvadratu, I will look into this, Thanks for your feedback

**Comment by devizee** [comment] 2022-11-22 23:14
I have the same problem, I hope it will be solved as soon as possible

**Comment by MohmmedAshraf** [comment] 2022-12-13 09:38
Hi there,

I'm sorry but I'm unable to reproduce the issue you're describing. I've tried following the steps outlined in the issue description, but I'm not seeing the same behavior that you're reporting, It would be helpful to have as much detail as possible so that others can try to reproduce the issue as well.

Thank you!

**Comment by elguitarraverde** [comment] 2023-01-02 22:56
I have investigated this and the problem is in the `blade-ui-kit/blade-icons` library.
You can work around the problem temporarily by caching the icons with the following command: `php artisan icons:cache`.

@MohmmedAshraf to reproduce the error you must execute the following command `php artisan icons:clear` and you will notice how Laravel becomes very slow.

Greetings.

**Comment by dkvadratu** [comment] 2023-01-03 07:13
> I have investigated this and the problem is in the `blade-ui-kit/blade-icons` library. You can work around the problem temporarily by caching the icons with the following command: `php artisan icons:cache`.
> 
> @MohmmedAshraf to reproduce the error you must execute the following command `php artisan icons:clear` and you will notice how Laravel becomes very slow.
> 
> Greetings.

I have tested. And yes icons cache fixes loading time. Thanks @elguitarraverde for investigation. How you finded out this?

**Comment by elguitarraverde** [comment] 2023-01-03 08:22
> I have tested. And yes icons cache fixes loading time. Thanks @elguitarraverde for investigation. How you finded out this?

@dkvadratu I first commented out some parts of the package code but got no results. then I was uninstalling and installing each dependency of the package until I located the package in question. I read the documentation for the icon pack and it has an option to cache the icons.

**Comment by MohmmedAshraf** [comment] 2023-01-09 11:57
Hi @elguitarraverde ,

Thank you for your help in investigating this issue, 
I will close this issue now since `php artisan icons:cache` did the trick

Thank you again for your assistance.

**Closed by MohmmedAshraf** 2023-01-09 11:57 UTC
Labels: information needed
